### ISSUE TITLE
恶堕魔法少女线条件问题

### ISSUE THREAD

**Issue by assassingyk** [DaiShengSheng/lifeRestart_bot#3]
如图，恶堕线后续事件仍是正常魔法少女事件，尝试在21457恶堕事件加了exclude条件好像也不好用，不知道为啥）
![PZ0$W40 O`3{N(6ZPM4T%~3](https://user-images.githubusercontent.com/55473115/132182496-6b5269bc-0ea0-430f-95ad-a03242c3ec79.png)

**Comment by DaiShengSheng** [comment]
奇怪了，没看出来有啥问题，反馈给隔壁了）

**Comment by cc004** [comment]
有什么问题吗，不是变回普通人了吗

**Comment by cc004** [comment]
明白了，是恶堕
