### ISSUE TITLE
__init__.py line 45 应该是 ‘/data’

### ISSUE THREAD

**Issue by Odeioikr** [DaiShengSheng/lifeRestart_bot#5]
会导致无法正常使用
`[2021-09-07 05:09:36，978 人生重来模拟器〕 ERROR: sClass IFileNotFoundError'> occured when remake handling messag
e 339.
[2021-09-07 05:09：36，979 人生重来模拟器〕 ERROR: TErrno 2] No such file or directory:
'/root/HoshinoBot/hoshino/
modules/lifeRestart_bot\\data/talents.json'
Traceback (most recent call last) :
File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
await sf. func (bot, event)
File
"/root/HoshinoBot/hoshino/service.py", line 218, in wrapper
return await func (bot, event)
File
"/root/HoshinoBot/hoshino/modules/lifeRestart_bot/__init__.py",line45,in remake
Life.load (FILE_PATH+'\ data')
File "/root/HoshinoBot/hoshino/modules/lifeRestart_bot/Life.py",
line 20, in load
with open(os.path. join(datapath,
"talents.json'), encoding='utf8') as fp:
FileNotFoundError: [Errno 2] No such file or directory:
/root/HoshinoBot/hoshino/modules/lifeRestart_bot\\data
/talents.json' `

**Comment by DaiShengSheng** [comment]
已修复
