### ISSUE TITLE
如何使结果不以转发形式发出？

### ISSUE THREAD

**Issue by as6296463** [DaiShengSheng/lifeRestart_bot#8]
如图1是转发发出形式，图2是想达成的效果
![B2C22858F184C54DC216AF8FCA6FFEB9](https://user-images.githubusercontent.com/37761817/140448095-ab980fa9-85c3-49e4-ab2d-2bf0bb9a5edd.jpg)
![image](https://user-images.githubusercontent.com/37761817/140448160-ee360149-9a18-4df0-b4f0-e2edacf5bc64.png)

**Comment by DaiShengSheng** [comment]
转发形式是在之前更新的时候更改的，直接发图片的话多张图片可能会触发风控，图片示例的是早期的版本
